/**
 * Writes sql/seed/02_ipl.sql from sql/data/ipl-fixtures.ts.
 * Run: npx tsx sql/scripts/build-ipl-seed.ts
 *
 * Fixtures: a round-robin "circle" schedule, so each team plays exactly once per
 * round and every team's match order follows the calendar.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { PLAYERS, SEASONS, TEAMS, type Team } from '../data/ipl-fixtures.js';

interface Match { id: number; season: number; date: string; home: Team; away: Team }

const teams = Object.keys(TEAMS) as Team[];

function addDays(iso: string, days: number): string {
  const d = new Date(`${iso}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

function roundPairs(round: number): Array<[Team, Team]> {
  const rest = teams.slice(1);
  const rotated = rest.slice(round % rest.length).concat(rest.slice(0, round % rest.length));
  const order = [teams[0], ...rotated];
  return Array.from({ length: order.length / 2 }, (_, i) => {
    const a = order[i];
    const b = order[order.length - 1 - i];
    return (round + i) % 2 === 0 ? [a, b] : [b, a];
  });
}

const matches: Match[] = [];
let roundOffset = 0;
for (const s of SEASONS) {
  for (let r = 0; r < s.rounds; r += 1) {
    roundPairs(roundOffset + r).forEach(([home, away], k) => {
      matches.push({ id: s.firstMatchId + r * 5 + k, season: s.season, date: addDays(s.firstDate, r * 6 + k), home, away });
    });
  }
  roundOffset += s.rounds;
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const lines: string[] = [
  '-- Scenario 2 seed data: SYNTHETIC IPL-style batting scores.',
  '-- Real player and team names for readability; every score and date is invented.',
  '-- GENERATED by sql/scripts/build-ipl-seed.ts from sql/data/ipl-fixtures.ts. Do not edit by hand.',
  '',
  'INSERT INTO players (player_id, player_name, team) VALUES',
  PLAYERS.map((p) => `  (${p.id}, ${q(p.name)}, ${q(p.team)})`).join(',\n') + ';',
  '',
  '-- 2024 fixtures are inserted before the 2023 ones on purpose: physical row order',
  '-- must never matter, only match_date does.',
  'INSERT INTO matches (match_id, season, match_date, home_team, away_team, venue) VALUES',
  [...matches.filter((m) => m.season === 2024), ...matches.filter((m) => m.season === 2023)]
    .map((m) => `  (${m.id}, ${m.season}, ${q(m.date)}, ${q(m.home)}, ${q(m.away)}, ${q(TEAMS[m.home])})`)
    .join(',\n') + ';',
  '',
];

for (const p of PLAYERS) {
  const rows: string[] = [];
  for (const [seasonText, scores] of Object.entries(p.runs)) {
    const season = Number(seasonText);
    const teamMatches = matches.filter((m) => m.season === season && (m.home === p.team || m.away === p.team));
    scores?.forEach((runs, i) => {
      if (runs === null) return;
      const match = teamMatches[i];
      if (!match) throw new Error(`${p.name} has more ${season} scores than ${p.team} has matches`);
      const balls = runs === 0 ? 2 : Math.max(1, Math.round(runs / p.strikeRate));
      rows.push(`  (${match.id}, ${p.id}, ${runs}, ${balls})  -- ${match.date} ${match.home} v ${match.away}`);
    });
  }
  if (p.insertInReverse) rows.reverse();
  const dnb = Object.entries(p.runs).flatMap(([s, scores]) => (scores ?? []).map((r, i) => (r === null ? `${s} match ${i + 1}` : null)).filter(Boolean));
  lines.push(`-- ${p.name} (${p.team}): ${p.proves}.`);
  if (dnb.length) lines.push(`--   Did not bat: ${dnb.join(', ')}.`);
  if (p.insertInReverse) lines.push('--   Rows deliberately inserted newest-first.');
  lines.push('INSERT INTO batting_innings (match_id, player_id, runs, balls) VALUES');
  lines.push(rows.map((r, i) => (i < rows.length - 1 ? r.replace('  --', ', --') : r.replace('  --', '; --'))).join('\n'));
  lines.push('');
}

const out = fileURLToPath(new URL('../seed/02_ipl.sql', import.meta.url));
writeFileSync(out, lines.join('\n'));
console.log(`Wrote ${matches.length} matches and ${PLAYERS.length} players to sql/seed/02_ipl.sql`);
