@sql
Feature: SQL scenario 2 - IPL 2024 players with 30+ runs in 3+ consecutive matches
  Return each player and the date the streak started. Query:
  sql/queries/scenario2_ipl_30plus_streaks.sql. Every run loads
  sql/schema/02_ipl.sql and sql/seed/02_ipl.sql into PostgreSQL 18 (PGlite).
  The scores are synthetic; each player in the seed exists to prove one rule.
  Expected rows come from an independent TypeScript oracle that reads the raw
  tables and walks each player's 2024 innings in date order.

  Background:
    Given the "IPL 2024" SQL scenario is loaded

  # Two oracles that must agree: the table below, worked out by hand from the seed, and the
  # TypeScript oracle. Each player in the seed exists to prove one rule.
  Scenario: The query returns exactly the streaks worked out by hand
    When I run the scenario query
    Then the result columns should be "player_name, streak_start_date, streak_end_date, streak_length"
    And the result should be exactly these streaks, worked out by hand:
      | player          | start      | end        | length | why                                                       |
      | Virat Kohli     | 2024-03-23 | 2024-04-19 | 5      | a 5-match streak is one row, not three 3-match windows    |
      | Ruturaj Gaikwad | 2024-03-28 | 2024-04-09 | 3      | exactly 3 matches, the last one exactly 30 runs           |
      | Phil Salt       | 2024-03-23 | 2024-04-04 | 3      | 30, 30, 30: 30 counts as 30+                              |
      | Travis Head     | 2024-03-22 | 2024-04-05 | 3      | first of two streaks in the season                        |
      | Travis Head     | 2024-04-19 | 2024-05-05 | 4      | second streak after a duck: both are reported             |
      | KL Rahul        | 2024-03-25 | 2024-04-09 | 3      | a match the player did not bat in is skipped              |
      | Rishabh Pant    | 2024-04-01 | 2024-04-12 | 3      | rows inserted newest-first are ordered by date            |
    And the result should match the independent oracle
    And the seed should hold these players, and none of them should be reported:
      | player          | why                                                       |
      | Abhishek Sharma | a 29 breaks what would otherwise be a 5-match run         |
      | Sanju Samson    | four 30+ scores, never two in a row                       |
      | Shubman Gill    | 36, 52 at the end of 2023 and 41, 33 at the start of 2024 |
      | Rohit Sharma    | big scores in isolation                                   |
      | Jasprit Bumrah  | a tail-ender with gaps and ducks                          |
      | Shashank Singh  | background player with no streak                          |

  Scenario: A plausible but wrong query is caught by the same checks
    The anti-pattern uses LAG/LEAD ("this innings and the ones either side are
    30+") and filters the season after the window. The oracle check must reject it.
    When I run the anti-pattern query "scenario2_lag_lead_windows"
    Then the result should not match the independent oracle
    And the result should have 11 rows
    And "Virat Kohli" should appear in exactly 3 rows
    And "Shubman Gill" should have a streak from "2023-05-18" to "2024-03-31" of 3 matches

  Scenario: Evidence - the query output screenshot is regenerated by this run
    When I render the query output screenshot
    Then the screenshot should show the oracle match and be attached to this report
