@sql
Feature: SQL scenario 1 - round-trip transfers (possible reversals)
  Account A sends money to account B, and B sends a similar amount (within 10%)
  back to A within 24 hours. Query: sql/queries/scenario1_round_trip_transfers.sql.
  Every run loads sql/schema/01_transactions.sql and sql/seed/01_transactions.sql
  into PostgreSQL 18 (PGlite, in-process). Expected rows come from an independent
  TypeScript oracle that reads the raw transactions and applies the same rules
  with integer paise and integer seconds, so the boundaries are exact.

  Background:
    Given the "round-trip transfers" SQL scenario is loaded

  # Two oracles that must agree: the table below, worked out by hand from the seed, and the
  # TypeScript oracle. Each guards the other against sharing a bug with the query. The seed
  # holds one transfer pair per rule; the near misses sit one second or one paisa past a limit.
  Scenario: The query returns exactly the round trips worked out by hand
    When I run the scenario query
    Then the result columns should be "account_a, account_b, sent_txn_id, sent_amount, sent_at, returned_txn_id, returned_amount, returned_at, hours_apart, pct_difference"
    And the result should be exactly these round trips, worked out by hand:
      | sent   | returned | hours | pct    | why                                                         |
      | TX0101 | TX0102   | 2.50  | 0.000  | same amount sent back 2.5 hours later                       |
      | TX0201 | TX0202   | 24.00 | 2.000  | sent back exactly 24 hours later (inclusive)                |
      | TX0401 | TX0402   | 6.00  | 10.000 | sent back exactly 10% less (inclusive)                      |
      | TX0501 | TX0502   | 12.00 | 10.000 | sent back exactly 10% more (inclusive)                      |
      | TX0701 | TX0702   | 2.00  | 0.000  | the earlier transfer is A, even when its account sorts last |
      | TX1001 | TX1002   | 2.00  | 2.000  | first of two qualifying returns                             |
      | TX1001 | TX1003   | 9.00  | 5.000  | second of two qualifying returns: both pairs are reported   |
      | TX1101 | TX1102   | 4.00  | 0.000  | chain A to B to A to B, first round trip                    |
      | TX1102 | TX1103   | 7.00  | 2.500  | chain A to B to A to B, the return starts a new round trip  |
      | TX1301 | TX1302   | 0.75  | 9.999  | odd paise just inside 10% (33.33 on 333.33)                 |
    And the result should match the independent oracle
    And the seed should hold these near misses, and none of them should be reported:
      | sent   | returned | why                                                             |
      | TX0301 | TX0302   | sent back 24 hours and 1 second later                           |
      | TX0601 | TX0602   | 10% less and one paisa more (17999.99 on 20000)                 |
      | TX0601 | TX0603   | 10% more and one paisa more (22000.01 on 20000)                 |
      | TX0702 | TX0701   | same pair read backwards: the return must come after            |
      | TX0102 | TX0101   | a round trip is reported once, never again with A and B swapped |
      | TX0801 | TX0802   | self-transfers (from = to) are not round trips                  |
      | TX0901 | TX0903   | a triangle A to B to C to A never sends money straight back     |
      | TX1201 | TX1202   | only 5% of the amount comes back                                |
      | TX1301 | TX1303   | odd paise just outside 10% (33.34 on 333.33)                    |

  Scenario: A plausible but wrong query is caught by the same checks
    The anti-pattern compares times with ABS() instead of "strictly later" and
    drops the self-transfer filter. The oracle check must reject it.
    When I run the anti-pattern query "scenario1_absolute_time_difference"
    Then the result should not match the independent oracle
    And the result should have 23 rows
    And sent transfer "TX0102" and return "TX0101" should be reported
    And sent transfer "TX0801" and return "TX0802" should be reported
    And sent transfer "TX0603" and return "TX0601" should be reported

  Scenario: Evidence - the query output screenshot is regenerated by this run
    When I render the query output screenshot
    Then the screenshot should show the oracle match and be attached to this report
